### ISSUE TITLE
Discussion for workshop

### ISSUE THREAD

**Issue by pyroar** [SJCaldwell/strongConnection#1]
For our discussion, would creating a markdown file and then turning it into a pretty PDF once we're done/happy with it be good for you?

**Comment by SJCaldwell** [comment]
Works for me. I've been meaning to get some more experience with workdown
anywho.



On Thu, Oct 22, 2015 at 11:21 PM, Richard Protasov <notifications@github.com

**Comment by pyroar** [comment]
Okay great, I'll add a file for it!
